---
- hosts: leafs
  connection: local
  gather_facts: no
  
  vars_files: vrf_design.yml

  tasks:
  - name: Configure L3 VXLAN VRF
    eos_config:
      src: vrf.j2

  - name: "Create vrf Configuration"
    template:
      src: vrf.j2
      dest: "{{config_dir}}/{{ inventory_hostname }}.cfg"
    delegate_to: localhost
    tags: vrf
