---
- name: "Create interface Configuration"
  template:
    src: interfaces.j2
    dest: "{{config_dir}}/{{ inventory_hostname }}.cfg"
  delegate_to: localhost
  tags: interfaces_configs

- name: "Create bgp Configuration"
  template:
    src: bgp.j2
    dest: "{{config_dir}}/{{ inventory_hostname }}.cfg"
  delegate_to: localhost
  tags: bgp_configs

- name: "Create EVPN Configuration"
  template:
    src: evpn.j2
    dest: "{{config_dir}}/{{ inventory_hostname }}.cfg"
  delegate_to: localhost
  tags: evpn_configs
  
- name: "Create MLAG Configuration"
  template:
    src: mlag.j2
    dest: "{{config_dir}}/{{ inventory_hostname }}.cfg"
  delegate_to: localhost
  tags: mlag_configs

# - name: "Deploy Configuration"
#   eos_config:
#     src: "{{config_dir}}/{{ inventory_hostname }}.cfg"
#     save_when: changed
#   tags: vxlan