asn: 65000
bgp_neighbors:
- neighbor: 10.0.1.2
  remote_as: 65001
  state: present
- neighbor: 10.0.1.6
  remote_as: 65001
  state: present
- neighbor: 10.0.1.10
  remote_as: 65002
  state: present
- neighbor: 10.0.1.14
  remote_as: 65002
  state: present
evpn_neighbors:
- neighbor: 10.0.250.11
  remote_as: 65001
  state: present
- neighbor: 10.0.250.12
  remote_as: 65001
  state: present
- neighbor: 10.0.250.13
  remote_as: 65002
  state: present
- neighbor: 10.0.250.14
  remote_as: 65002
  state: present
hostname: dc1-spine1
interfaces:
- address: 10.0.1.1
  description: leaf1
  interface: Ethernet1
  mask: /30
- address: 10.0.1.5
  description: leaf2
  interface: Ethernet2
  mask: /30
- address: 10.0.1.9
  description: leaf3
  interface: Ethernet3
  mask: /30
- address: 10.0.1.13
  description: leaf4
  interface: Ethernet4
  mask: /31
loopback0_ip: 10.0.250.1
